-- =====================================================================
-- Assignment 10 - Car Rental & Fleet Booking System (Supabase)
-- Run this whole script once in: Supabase Dashboard -> SQL Editor -> New query
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. VEHICLES TABLE
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand TEXT NOT NULL,
    model TEXT NOT NULL,
    year INT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Sedan', 'SUV', 'Luxury', 'Hatchback', 'Electric')),
    daily_rate NUMERIC(10, 2) NOT NULL CHECK (daily_rate > 0),
    fuel_type TEXT NOT NULL,
    seating_capacity INT NOT NULL DEFAULT 5,
    status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'rented', 'maintenance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 2. RENTALS / BOOKINGS TABLE
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rentals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- references Supabase auth.users
    vehicle_id BIGINT REFERENCES vehicles(id) ON DELETE RESTRICT,
    customer_name TEXT NOT NULL,
    customer_email TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_cost NUMERIC(10, 2) NOT NULL,
    status TEXT NOT NULL DEFAULT 'booked' CHECK (status IN ('booked', 'active', 'completed', 'cancelled')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT valid_date_range CHECK (end_date >= start_date)
);

-- Indexes used to make date-collision lookups fast
CREATE INDEX IF NOT EXISTS idx_rentals_vehicle_dates ON rentals (vehicle_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_rentals_user ON rentals (user_id);

-- ---------------------------------------------------------------------
-- 3. PROFILES TABLE (holds display name, auto-created on signup)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    email TEXT,
    name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Auto-create a profile row whenever a new auth user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, email, name)
    VALUES (NEW.id, NEW.email, NEW.raw_user_meta_data->>'name');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ---------------------------------------------------------------------
-- 4. ROW LEVEL SECURITY
-- ---------------------------------------------------------------------

-- --- VEHICLES ---
-- Fleet browsing is public (GET /api/vehicles needs no auth).
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "vehicles_public_read" ON vehicles;
CREATE POLICY "vehicles_public_read"
    ON vehicles FOR SELECT
    USING (true);

-- Vehicle management (create/update/delete) requires an authenticated user.
DROP POLICY IF EXISTS "vehicles_auth_insert" ON vehicles;
CREATE POLICY "vehicles_auth_insert"
    ON vehicles FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "vehicles_auth_update" ON vehicles;
CREATE POLICY "vehicles_auth_update"
    ON vehicles FOR UPDATE
    USING (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "vehicles_auth_delete" ON vehicles;
CREATE POLICY "vehicles_auth_delete"
    ON vehicles FOR DELETE
    USING (auth.uid() IS NOT NULL);

-- --- RENTALS ---
ALTER TABLE rentals ENABLE ROW LEVEL SECURITY;

-- Read policies:
--  * authenticated users can always read their OWN bookings (booking-history protection)
--  * anon/public reads are allowed only so the public "GET /api/vehicles/:id"
--    endpoint can show past rental records for a car.
DROP POLICY IF EXISTS "rentals_owner_read" ON rentals;
CREATE POLICY "rentals_owner_read"
    ON rentals FOR SELECT
    USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "rentals_anon_read_vehicle_history" ON rentals;
CREATE POLICY "rentals_anon_read_vehicle_history"
    ON rentals FOR SELECT
    USING (true);

-- A user can only book a vehicle FOR THEMSELVES (user_id must equal their JWT sub)
DROP POLICY IF EXISTS "rentals_insert_own" ON rentals;
CREATE POLICY "rentals_insert_own"
    ON rentals FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Only the owner can cancel / complete their own rental
DROP POLICY IF EXISTS "rentals_owner_update" ON rentals;
CREATE POLICY "rentals_owner_update"
    ON rentals FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- --- PROFILES ---
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select_own" ON profiles;
CREATE POLICY "profiles_select_own"
    ON profiles FOR SELECT
    USING (auth.uid() = id);

-- ---------------------------------------------------------------------
-- 5. SEED DATA (3 sample vehicles as required by the testing guide)
-- ---------------------------------------------------------------------
INSERT INTO vehicles (brand, model, year, category, daily_rate, fuel_type, seating_capacity) VALUES
    ('Toyota',  'Camry',     2024, 'Sedan',     4500.00, 'Petrol',  5),
    ('Tesla',   'Model 3',   2024, 'Electric',  4500.00, 'EV',      5),
    ('Hyundai', 'Creta',     2025, 'SUV',       5000.00, 'Diesel',  5)
ON CONFLICT DO NOTHING;